{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8874b5df-7443-45ac-896e-bae329471154",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n",
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n",
      "2026-04-16 00:16:33.398 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.987 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\savai\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-04-16 00:16:35.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.992 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:35.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.000 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.001 Session state does not function when running a script without `streamlit run`\n",
      "2026-04-16 00:16:36.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.004 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.007 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.009 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-16 00:16:36.010 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing import image\n",
    "from PIL import Image\n",
    "\n",
    "# Load models (update paths if needed)\n",
    "cnn_model = tf.keras.models.load_model(\"cnn_model.h5\")\n",
    "tl_model = tf.keras.models.load_model(\"tl_model.h5\")\n",
    "\n",
    "# Class labels (same as training)\n",
    "class_labels = [\n",
    "    \"aerosol_cans\", \"aluminum_food_cans\", \"aluminum_soda_cans\",\n",
    "    \"cardboard_boxes\", \"cardboard_packaging\", \"clothing\",\n",
    "    \"coffee_grounds\", \"disposable_plastic_cutlery\", \"eggshells\",\n",
    "    \"food_waste\", \"glass_beverage_bottles\", \"glass_cosmetic_containers\",\n",
    "    \"glass_food_jars\", \"magazines\", \"newspaper\", \"office_paper\",\n",
    "    \"paper_cups\", \"plastic_cup_lids\", \"plastic_detergent_bottles\",\n",
    "    \"plastic_food_containers\", \"plastic_shopping_bags\",\n",
    "    \"plastic_soda_bottles\", \"plastic_straws\", \"plastic_trash_bags\",\n",
    "    \"plastic_water_bottles\", \"shoes\", \"steel_food_cans\",\n",
    "    \"styrofoam_cups\", \"styrofoam_food_containers\", \"tea_bags\"\n",
    "]\n",
    "\n",
    "# Category mapping (Recycle / Reduce / Reuse)\n",
    "def map_category(cls):\n",
    "    recycle = [\n",
    "        \"aerosol_cans\",\"aluminum_food_cans\",\"aluminum_soda_cans\",\n",
    "        \"glass_beverage_bottles\",\"glass_cosmetic_containers\",\"glass_food_jars\",\n",
    "        \"plastic_bottles\",\"plastic_food_containers\",\"steel_food_cans\",\n",
    "        \"cardboard_boxes\",\"cardboard_packaging\"\n",
    "    ]\n",
    "    \n",
    "    reuse = [\n",
    "        \"clothing\",\"shoes\",\"newspaper\",\"magazines\",\"office_paper\",\"paper_cups\"\n",
    "    ]\n",
    "    \n",
    "    if cls in recycle:\n",
    "        return \"♻ Recycle\"\n",
    "    elif cls in reuse:\n",
    "        return \"🔁 Reuse\"\n",
    "    else:\n",
    "        return \"🚯 Reduce / Waste\"\n",
    "\n",
    "# Prediction function\n",
    "def predict(model, img):\n",
    "    img = img.resize((224, 224))\n",
    "    img_array = image.img_to_array(img) / 255.0\n",
    "    img_array = np.expand_dims(img_array, axis=0)\n",
    "\n",
    "    prediction = model.predict(img_array)\n",
    "    class_index = np.argmax(prediction)\n",
    "\n",
    "    return class_labels[class_index]\n",
    "\n",
    "# Streamlit UI\n",
    "st.title(\"🗑 Waste Classification App\")\n",
    "st.write(\"Upload an image and get waste category prediction\")\n",
    "\n",
    "model_choice = st.radio(\"Choose Model\", [\"CNN Model\", \"Pretrained Model\"])\n",
    "\n",
    "uploaded_file = st.file_uploader(\"Upload Image\", type=[\"jpg\", \"png\", \"jpeg\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "    img = Image.open(uploaded_file)\n",
    "    st.image(img, caption=\"Uploaded Image\", use_container_width=True)\n",
    "\n",
    "    if st.button(\"Predict\"):\n",
    "        if model_choice == \"CNN Model\":\n",
    "            result = predict(cnn_model, img)\n",
    "        else:\n",
    "            result = predict(tl_model, img)\n",
    "\n",
    "        category = map_category(result)\n",
    "\n",
    "        st.success(f\"Predicted Class: {result}\")\n",
    "        st.info(f\"Category: {category}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dabbc2f4-c318-4b36-b18f-08c5f9d1244d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
